package:
  name: worker-build
  version: 0.8.7
  epoch: 0
  description: build Rust Cloudflare Workers into WASM binaries.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - wasm-pack
      - wasm-bindgen

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - openssl-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 454fbd3c6ba3109be6158b19a04102abfcabfef1
      repository: https://github.com/cloudflare/workers-rs
      tag: v${{package.version}}
      recurse-submodules: true
  - uses: cargo/build
    with:
      modroot: worker-build
      output: ${{package.name}}
